const SPREADSHEET_ID='REPLACE_WITH_YOUR_GOOGLE_SHEET_ID';
const RESPONSE_SHEET='Students', PAIR_SHEET='Pair Scores', DASHBOARD_SHEET='Staff Dashboard', MATCH_SHEET='Match Cards';
function setup(){const ss=SpreadsheetApp.openById(SPREADSHEET_ID);sheet_(ss,RESPONSE_SHEET,['Timestamp','Full Name','Email','School','Year','Major','Hometown','Interests','Talk About','Social Style','Friend Style','Faith Position','Faith Comfort','Faith Topics','Culture Curiosity','Culture Share','Meaningful Friendship','Availability','Frequency','Fun Question','Anything Else','Consent','Status']);sheet_(ss,PAIR_SHEET,['Score','SVF Student','NPU Student','Interests','Availability','Social Style','Faith','Culture','Other','Notes']);sheet_(ss,DASHBOARD_SHEET,['SVF Student','NPU Student','Score','Status','Why This Match']);sheet_(ss,MATCH_SHEET,['SVF Student','NPU Student','Score','Match Card'])}
function doGet(){return HtmlService.createHtmlOutput('<p>SVF–NPU submission service is running.</p>')}
function doPost(e){try{if(e.parameter.website)return HtmlService.createHtmlOutput('OK');const p=e.parameter,ps=e.parameters,ss=SpreadsheetApp.openById(SPREADSHEET_ID),sh=ss.getSheetByName(RESPONSE_SHEET)||sheet_(ss,RESPONSE_SHEET,[]);sh.appendRow([new Date(),s(p.fullName),s(p.email),s(p.school),s(p.year),s(p.major),s(p.hometown),arr(ps.interests),s(p.talkAbout),s(p.socialStyle),arr(ps.friendStyle),s(p.faithPosition),s(p.faithComfort),arr(ps.faithTopics),s(p.cultureCuriosity),s(p.cultureShare),s(p.meaningful),arr(ps.availability),s(p.frequency),s(p.funQuestion),s(p.anythingElse),s(p.consent),'New']);refresh_();return HtmlService.createHtmlOutput('Thank you. Your response has been received.')}catch(err){return HtmlService.createHtmlOutput('Submission could not be processed. Please contact the coordinator.')}}
function refresh_(){const ss=SpreadsheetApp.openById(SPREADSHEET_ID),students=read_(ss),a=students.filter(x=>x.school==='SVF'),b=students.filter(x=>x.school==='NPU'),pairs=[];a.forEach(x=>b.forEach(y=>{const d=score_(x,y);pairs.push({a:x,b:y,d,score:d.total})}));pairs.sort((x,y)=>y.score-x.score);const ps=ss.getSheetByName(PAIR_SHEET);clear_(ps);pairs.forEach(x=>ps.appendRow([x.score,x.a.name,x.b.name,x.d.interests,x.d.availability,x.d.social,x.d.faith,x.d.culture,x.d.other,x.d.notes]));const usedA=new Set,usedB=new Set,chosen=[];for(const x of pairs){if(!usedA.has(x.a.email)&&!usedB.has(x.b.email)){usedA.add(x.a.email);usedB.add(x.b.email);chosen.push(x)}}const dash=ss.getSheetByName(DASHBOARD_SHEET);clear_(dash);chosen.forEach(x=>dash.appendRow([x.a.name,x.b.name,x.score,'Suggested',reason_(x)]));const cards=ss.getSheetByName(MATCH_SHEET);clear_(cards);chosen.forEach(x=>cards.appendRow([x.a.name,x.b.name,x.score,card_(x)]))}
function read_(ss){const sh=ss.getSheetByName(RESPONSE_SHEET);if(!sh||sh.getLastRow()<2)return[];const v=sh.getDataRange().getValues(),h=v.shift();return v.map((r,i)=>{let o={};h.forEach((k,j)=>o[k]=r[j]);return{row:i+2,name:String(o['Full Name']||''),email:String(o.Email||''),school:String(o.School||''),interests:set(o.Interests),availability:set(o.Availability),social:String(o['Social Style']||''),friendStyle:set(o['Friend Style']),faithComfort:String(o['Faith Comfort']||''),frequency:String(o.Frequency||'')}}).filter(x=>x.name&&x.email&&x.school)}
function score_(a,b){const interests=Math.round(overlap(a.interests,b.interests)*25),availability=Math.round(overlap(a.availability,b.availability)*20),social=social_(a.social,b.social),faith=faith_(a.faithComfort,b.faithComfort),culture=10,other=Math.min(10,(a.frequency===b.frequency?8:5)+(overlap(a.friendStyle,b.friendStyle)>0?2:0));return{total:Math.min(100,interests+availability+social+faith+culture+other),interests,availability,social,faith,culture,other,notes:[...a.interests].filter(x=>b.interests.has(x)).join(', ')}}
function social_(a,b){if(a===b)return 20;if(a.includes('depends')||b.includes('depends'))return 16;if((a.includes('easily')&&b.includes('meeting'))||(b.includes('easily')&&a.includes('meeting')))return 16;if((a.includes('quieter')&&b.includes('meeting'))||(b.includes('quieter')&&a.includes('meeting')))return 14;return 10}
function faith_(a,b){if(a===b)return 15;if(a.includes('naturally')||b.includes('naturally'))return 13;if(a.includes('Somewhat')||b.includes('Somewhat'))return 12;return 9}
function overlap(a,b){if(!a.size||!b.size)return 0;const i=[...a].filter(x=>b.has(x)).length,u=new Set([...a,...b]).size;return u?i/u:0}
function reason_(x){const p=[];if(x.d.interests>=15)p.push('strong shared interests');if(x.d.availability>=12)p.push('good schedule overlap');if(x.d.social>=16)p.push('compatible social styles');if(x.d.faith>=12)p.push('compatible comfort discussing faith');return p.join('; ')||'potential compatibility; review profiles'}
function card_(x){const shared=[...x.a.interests].filter(i=>x.b.interests.has(i)).join(', ')||'Explore each other’s interests';const times=[...x.a.availability].filter(i=>x.b.availability.has(i)).join(', ')||'Find a mutually convenient time';return 'WHY THIS MATCH MAY WORK\n'+reason_(x)+'\n\nSHARED INTERESTS\n'+shared+'\n\nSHARED AVAILABILITY\n'+times+'\n\nFIRST MEETING IDEA\nTry coffee, a meal, a walk, an activity, or another low-pressure way to talk.'}
function set(v){return new Set(String(v||'').split(',').map(x=>x.trim()).filter(Boolean))}function arr(v){return Array.isArray(v)?v.join(', '):String(v||'')}function s(v){return String(v||'').trim().substring(0,5000)}function sheet_(ss,n,h){let x=ss.getSheetByName(n);if(!x)x=ss.insertSheet(n);if(h.length&&!x.getLastRow())x.appendRow(h);return x}function clear_(x){if(x&&x.getLastRow()>1)x.getRange(2,1,x.getLastRow()-1,x.getLastColumn()).clearContent()}
